FROM registry.svc.ci.openshift.org/ocp/builder:golang-1.11 AS builder
WORKDIR /go/src/github.com/kubernetes-csi/external-resizer
COPY . .
RUN go build ./cmd/csi-resizer

FROM registry.svc.ci.openshift.org/ocp/4.0:base
COPY --from=builder /go/src/github.com/kubernetes-csi/external-resizer/csi-resizer /usr/bin/
RUN useradd csi-resizer
USER csi-resizer
ENTRYPOINT ["/usr/bin/csi-resizer"]
